import Vue from 'vue';
import Vuex from 'vuex';

Vue.use(Vuex);

const state = {
	all_submissions: [
		{
			time: '1 month ago',
			problem: 'Reverse a binary tree',
			result: 'Wrong Answer',
			runtime: 'NA',
			memory: 'NA',
			language: 'C++',
			id: '1',
			test_cases: [4, 10],
		},
		{
			time: '2 month ago',
			problem: 'House Robbers II',
			result: 'Runtime Error',
			runtime: 'NA',
			memory: 'NA',
			language: 'C++',
			id: '2',
			test_cases: [0, 10],
		},
		{
			time: '3 weeks agp',
			problem: 'Find least number of strings',
			result: 'Accepted',
			runtime: '24ms',
			memory: '292MB',
			language: 'C++',
			id: '3',
			test_cases: [10, 10],
		},
		{
			time: '4 weeks ago',
			problem: 'Reverse a binary tree',
			result: 'Time Limit Exceeded',
			runtime: 'NA',
			memory: 'NA',
			language: 'C++',
			id: '4',
			test_cases: [0, 10],
		},
		{
			time: '1 month ago',
			problem: 'Minimum Path Sum',
			result: 'Memory Limit Exceeded',
			runtime: 'NA',
			memory: 'NA',
			language: 'C++',
			id: '5',
			test_cases: [5, 10],
		},
		{
			time: '1 month ago',
			problem: 'Reverse a Linked List',
			result: 'Accepted',
			runtime: '24ms',
			memory: '295MB',
			language: 'C++',
			id: '6',
			test_cases: [10, 10],
		},
		{
			time: '1 month ago',
			problem: 'Reverse a binary tree',
			result: 'Accepted',
			runtime: '25ms',
			memory: '190MB',
			language: 'C++',
			id: '7',
			test_cases: [10, 10],
		},
		{
			time: '5 month ago',
			problem: 'Reverse a binary tree',
			result: 'Accepted',
			runtime: '24ms',
			memory: '296MB',
			language: 'C++',
			id: '8',
			test_cases: [10, 10],
		},
		{
			time: '1 year ago',
			problem: 'Reverse a binary tree',
			result: 'Accepted',
			runtime: '22ms',
			memory: '497MB',
			language: 'C++',
			id: '9',
			test_cases: [10, 10],
		},
	],
};

export default new Vuex.Store({
	state: state,
	mutations: {},
	actions: {},
	modules: {},
});
